version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-uplinkr
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./tunnels:/etc/nginx/tunnels:ro
      - ./uplinkr:/etc/nginx/sites-enabled/uplinkr:ro
      - ./uplinkr-wildcard:/etc/nginx/sites-enabled/uplinkr-wildcard:ro
      - ./uplinkr-ws-server:/etc/nginx/sites-enabled/uplinkr-ws-server:ro
    restart: unless-stopped